NORMALIZATION_RANGE = -1.0, 1.0
LEARNING_RATE = 0.2
MAX_EPOCHS = 30

FIG_WIDTH = 10
FIG_HEIGHT = 6
FIG_SUPERIOR_TITLE = "Perceptron training algorithm"
MAIN_SUBPLOT_TITLE = "Perceptron"
ERRORS_SUBPLOT_TITLE = "Errors through epochs"
ERRORS_SUBPLOT_XLABEL = "Epochs"
ERRORS_SUBPLOT_YLABEL = "No. of errors"

MAIN_SUBPLOT_PAUSE_INTERVAL = 0.1
ERRORS_SUBPLOT_PAUSE_INTERVAL = 0.3

PERCEPTRON_CONVERGED_TEXT = 'Perceptron converged'
PERCEPTRON_DIDNT_CONVERGE_TEXT = "Perceptron couldn't converge"
PERCEPTRON_CONVERGENCE_TEXT_FONT_SIZE = 10
PERCEPTRON_CONVERGENCE_TEXT_X_POS = -0.25
PERCEPTRON_CONVERGENCE_TEXT_Y_POS = 0.9
CONVERGENCE_OFFSET = 0.25

CURRENT_EPOCH_TEXT = 'Epoch: %s'
CURRENT_EPOCH_TEXT_FONT_SIZE = 10
CURRENT_EPOCH_TEXT_X_POS = 0.5
CURRENT_EPOCH_TEXT_Y_POS = 0.8

CLASS_0_MARKER = 'bx'
CLASS_1_MARKER = 'r.'
CLASS_0_MARKER_POST_FIT = 'kx'
CLASS_1_MARKER_POST_FIT = 'k.'
DECISION_BOUNDARY_MARKER = 'y-'

TEXT_BOX_LEARNING_RATE_AXES = [0.275, 0.15, 0.175, 0.05]
TEXT_BOX_LEARNING_RATE_PROMPT = "Learning rate (η):"
TEXT_BOX_MAX_EPOCHS_AXES = [0.7125, 0.15, 0.15, 0.05]
TEXT_BOX_MAX_EPOCHS_PROMPT = "Max no. of epochs:"
BUTTON_WEIGHTS_AXES = [0.225, 0.05, 0.125, 0.05]
BUTTON_WEIGHTS_TEXT = "Initialize Weights"
BUTTON_PERCEPTRON_AXES = [0.4625, 0.05, 0.1, 0.05]
BUTTON_PERCEPTRON_TEXT = "Perceptron"
